CREATE TABLE vehicle (
    veh_reg VARCHAR(8),
    make VARCHAR(20),
    model VARCHAR(20),
    colour VARCHAR(20),
    PRIMARY KEY (veh_reg)
);

INSERT INTO vehicle VALUES ("OY05 RLF","Nissan","Mustang Mach-E","Black");
INSERT INTO vehicle VALUES ("HD08 GEY","Kia","Transit Custom","Silver");
INSERT INTO vehicle VALUES ("PR65 AFN","Skoda","Scorpio","Silver");
INSERT INTO vehicle VALUES ("YG55 CGK","Volkwagen","Tourneo Courier","Silver");
INSERT INTO vehicle VALUES ("SM09 HCA","Ford","Maverick","Silver");
INSERT INTO vehicle VALUES ("WD11 YGV","Kia","Ka","Red");
INSERT INTO vehicle VALUES ("RV08 MWK","Hyundai","Sierra Sapphire","Black");
INSERT INTO vehicle VALUES ("BO13 ALB","Renualt","Sierra","Blue");
INSERT INTO vehicle VALUES ("PA54 FNR","Skoda","Kuga","Blue");
INSERT INTO vehicle VALUES ("SK70 OBW","Nissan","Fiesta","Green");
INSERT INTO vehicle VALUES ("HD09 SGB","Volkwagen","Tourneo Connect","Silver");
INSERT INTO vehicle VALUES ("YY19 WMG","Ford","Ka","White");
INSERT INTO vehicle VALUES ("KG19 HEH","Honda","StreetKa","Blue");
INSERT INTO vehicle VALUES ("WA55 KWR","Kia","EcoSport","Yellow");
INSERT INTO vehicle VALUES ("AV14 SNR","Skoda","Mustang Mach-E","Green");
INSERT INTO vehicle VALUES ("AH67 OKG","Skoda","Explorer","Green");
INSERT INTO vehicle VALUES ("CE06 FBH","Volkwagen","Probe","Red");
INSERT INTO vehicle VALUES ("SR04 CBW","Volkwagen","Probe","Green");
INSERT INTO vehicle VALUES ("EK12 FPR","Kia","Grand Tourneo Connect","Red");
INSERT INTO vehicle VALUES ("WK16 BPO","Volkwagen","Galaxy","Yellow");
INSERT INTO vehicle VALUES ("GH16 VDE","Vauxhall","Orion","Green");
INSERT INTO vehicle VALUES ("YB18 AMM","Vauxhall","Sierra Sapphire","Silver");
INSERT INTO vehicle VALUES ("MV15 HRA","Ford","Probe","Silver");
INSERT INTO vehicle VALUES ("LD69 MBP","Ford","Transit Custom","Silver");
INSERT INTO vehicle VALUES ("NG07 VSN","Vauxhall","StreetKa","Green");
INSERT INTO vehicle VALUES ("ER08 VFC","Ford","S-MAX","Blue");
INSERT INTO vehicle VALUES ("LO06 WLF","Nissan","Sierra","Green");
INSERT INTO vehicle VALUES ("HR57 KRD","Renualt","S-MAX","Red");
INSERT INTO vehicle VALUES ("DB58 GFV","Hyundai","Orion","Blue");
INSERT INTO vehicle VALUES ("WE64 RMP","Renualt","Transit Courier Kombi","Blue");
INSERT INTO vehicle VALUES ("WL67 VYK","Hyundai","B-MAX","Silver");
INSERT INTO vehicle VALUES ("CG55 MVN","Skoda","Galaxy","Blue");
INSERT INTO vehicle VALUES ("LL07 HBE","Nissan","StreetKa","Blue");
INSERT INTO vehicle VALUES ("WD16 WLL","Volkwagen","Galaxy","Red");
INSERT INTO vehicle VALUES ("HS54 KPP","Renualt","Tourneo Courier","White");
INSERT INTO vehicle VALUES ("BL05 FML","Renualt","Escort","Yellow");
INSERT INTO vehicle VALUES ("DE12 WWY","Renualt","Ka","White");
INSERT INTO vehicle VALUES ("EN57 CKV","Ford","Grand Tourneo Connect","Yellow");
INSERT INTO vehicle VALUES ("GF09 BRS","Honda","Focus C-MAX","Black");
INSERT INTO vehicle VALUES ("GP10 PFR","Vauxhall","Transit Courier Kombi","White");
INSERT INTO vehicle VALUES ("WY61 DPL","Kia","Kuga","Red");
INSERT INTO vehicle VALUES ("CR69 ELL","Renualt","Probe","Blue");
INSERT INTO vehicle VALUES ("YE02 DYF","Volkwagen","Galaxy","Yellow");
INSERT INTO vehicle VALUES ("WG07 LMC","Toyota","Escort","Silver");
INSERT INTO vehicle VALUES ("ON09 BSN","Kia","Ka","Yellow");
INSERT INTO vehicle VALUES ("MY55 PBN","Renualt","Fusion","White");
INSERT INTO vehicle VALUES ("DM06 VBB","Volkwagen","Puma","Silver");
INSERT INTO vehicle VALUES ("KK64 FGP","Kia","Cougar","Green");
INSERT INTO vehicle VALUES ("VB18 GFO","Hyundai","StreetKa","Green");
INSERT INTO vehicle VALUES ("NF02 BKP","Honda","Sierra","Blue");
INSERT INTO vehicle VALUES ("LY11 OYV","Ford","Tourneo Courier","Black");
INSERT INTO vehicle VALUES ("YY52 BHP","Ford","Transit Custom","Blue");
INSERT INTO vehicle VALUES ("HN68 LHN","Kia","Sierra Sapphire","Red");
INSERT INTO vehicle VALUES ("FG58 CMB","Vauxhall","Focus","Black");
INSERT INTO vehicle VALUES ("LA03 HEK","Hyundai","StreetKa","White");
INSERT INTO vehicle VALUES ("AP65 GMO","Vauxhall","Galaxy","Yellow");
INSERT INTO vehicle VALUES ("NH07 EHW","Nissan","Ka","Silver");
INSERT INTO vehicle VALUES ("WS65 BYF","Nissan","Explorer","Silver");
INSERT INTO vehicle VALUES ("BM06 SKK","Kia","Puma","Blue");
INSERT INTO vehicle VALUES ("ES08 SVY","Skoda","Granada","Silver");
INSERT INTO vehicle VALUES ("SW02 AYF","Hyundai","Capri","Silver");
INSERT INTO vehicle VALUES ("OA06 PSN","Ford","Maverick","White");
INSERT INTO vehicle VALUES ("PR12 FOE","Nissan","Cougar","Green");
INSERT INTO vehicle VALUES ("BS15 AEO","Nissan","C-MAX","Green");
INSERT INTO vehicle VALUES ("PG07 WKL","Nissan","Puma","Blue");
INSERT INTO vehicle VALUES ("DH08 FOW","Nissan","Galaxy","Yellow");
INSERT INTO vehicle VALUES ("RC66 RGE","Hyundai","S-MAX","Yellow");
INSERT INTO vehicle VALUES ("LO06 MFP","Volkwagen","Tourneo Connect","Black");
INSERT INTO vehicle VALUES ("HB55 PON","Toyota","Probe","White");
INSERT INTO vehicle VALUES ("NB54 BOS","Ford","Fusion","Green");
INSERT INTO vehicle VALUES ("LB60 FBF","Nissan","Transit Courier Kombi","Red");
INSERT INTO vehicle VALUES ("WP52 MMV","Kia","Grand C-MAX","Blue");
INSERT INTO vehicle VALUES ("GV61 PPS","Renualt","Scorpio","Black");
INSERT INTO vehicle VALUES ("CN04 VVG","Renualt","C-MAX","Yellow");
INSERT INTO vehicle VALUES ("DC15 FRL","Honda","Sierra Sapphire","Black");
INSERT INTO vehicle VALUES ("OV56 EDD","Ford","Kuga","White");
INSERT INTO vehicle VALUES ("LE16 ROK","Honda","Transit Courier Kombi","Red");
INSERT INTO vehicle VALUES ("DK70 LBC","Ford","EcoSport","Yellow");
INSERT INTO vehicle VALUES ("WA05 KLK","Renualt","Tourneo Connect","Green");
INSERT INTO vehicle VALUES ("FG15 LOR","Ford","Focus","Yellow");
INSERT INTO vehicle VALUES ("HN62 SDC","Ford","Mustang","Yellow");
INSERT INTO vehicle VALUES ("MV64 DDV","Vauxhall","Escort","Yellow");
INSERT INTO vehicle VALUES ("OG13 CLF","Renualt","Mustang Mach-E","Yellow");
INSERT INTO vehicle VALUES ("LW02 GBB","Hyundai","StreetKa","Red");
INSERT INTO vehicle VALUES ("RO10 DFP","Honda","Cougar","Black");
INSERT INTO vehicle VALUES ("FK68 CDL","Renualt","Grand C-MAX","Green");
INSERT INTO vehicle VALUES ("VY60 ONW","Skoda","S-MAX","Silver");
INSERT INTO vehicle VALUES ("NW65 BCL","Renualt","Kuga","Black");
INSERT INTO vehicle VALUES ("BD66 RPF","Vauxhall","Mondeo","Blue");
INSERT INTO vehicle VALUES ("BW63 PPF","Skoda","Fiesta","Red");
INSERT INTO vehicle VALUES ("WL70 CCG","Volkwagen","Maverick","Silver");
INSERT INTO vehicle VALUES ("NE10 YSP","Vauxhall","B-MAX","Green");
INSERT INTO vehicle VALUES ("VY17 FWW","Hyundai","Explorer","Green");
INSERT INTO vehicle VALUES ("YK59 DWV","Renualt","Grand C-MAX","White");
INSERT INTO vehicle VALUES ("LC04 NEY","Nissan","Mondeo","White");
INSERT INTO vehicle VALUES ("PN61 WFB","Hyundai","Granada","Green");
INSERT INTO vehicle VALUES ("BS02 FEY","Vauxhall","Ka","White");
INSERT INTO vehicle VALUES ("PF05 NMY","Volkwagen","Scorpio","Green");
INSERT INTO vehicle VALUES ("EE67 EKW","Skoda","Tourneo Connect","Green");
INSERT INTO vehicle VALUES ("RE14 FAY","Honda","Mustang","Blue");
INSERT INTO vehicle VALUES ("LG04 SLH","Volkwagen","Fusion","Green");
INSERT INTO vehicle VALUES ("BV14 OAM","Honda","Orion","Blue");
INSERT INTO vehicle VALUES ("YS63 CDL","Volkwagen","Fiesta","White");
INSERT INTO vehicle VALUES ("HW66 GMW","Kia","StreetKa","Silver");
INSERT INTO vehicle VALUES ("HA70 SGS","Renualt","Sierra","Red");
INSERT INTO vehicle VALUES ("MG70 FLY","Honda","StreetKa","Red");
INSERT INTO vehicle VALUES ("KV07 MOY","Volkwagen","Escort","Blue");
INSERT INTO vehicle VALUES ("VO10 PGH","Vauxhall","Galaxy","Silver");
INSERT INTO vehicle VALUES ("OK06 RYG","Volkwagen","Sierra Sapphire","Blue");
INSERT INTO vehicle VALUES ("GG66 VPC","Toyota","Capri","Green");
INSERT INTO vehicle VALUES ("EW05 AHM","Kia","Kuga","White");
INSERT INTO vehicle VALUES ("OC06 YOP","Toyota","Escort","Red");
INSERT INTO vehicle VALUES ("PE18 SYL","Kia","Kuga","Red");
INSERT INTO vehicle VALUES ("LO66 BRS","Skoda","Mustang Mach-E","Yellow");
INSERT INTO vehicle VALUES ("GV12 FYW","Ford","Grand C-MAX","Silver");
INSERT INTO vehicle VALUES ("MK67 KWF","Kia","Granada","White");
INSERT INTO vehicle VALUES ("SN09 CRS","Vauxhall","Transit Courier Kombi","Green");
INSERT INTO vehicle VALUES ("FS04 ENV","Renualt","Cougar","Yellow");
INSERT INTO vehicle VALUES ("MK55 LSP","Ford","Tourneo Connect","Blue");
INSERT INTO vehicle VALUES ("ES57 KVN","Toyota","Orion","Silver");
INSERT INTO vehicle VALUES ("BD70 RYA","Skoda","Edge","Silver");
INSERT INTO vehicle VALUES ("AA05 BRB","Hyundai","Ka","Blue");
INSERT INTO vehicle VALUES ("RS54 BAD","Kia","Fusion","White");
INSERT INTO vehicle VALUES ("EH55 MAW","Renualt","Capri","Red");
INSERT INTO vehicle VALUES ("OA58 RGL","Ford","Galaxy","Blue");
INSERT INTO vehicle VALUES ("RY68 BHS","Skoda","Grand C-MAX","Yellow");
INSERT INTO vehicle VALUES ("CG67 GEW","Skoda","B-MAX","Yellow");
INSERT INTO vehicle VALUES ("FO66 GEE","Kia","Capri","Green");
INSERT INTO vehicle VALUES ("WE57 NEG","Renualt","Grand Tourneo Connect","Green");
INSERT INTO vehicle VALUES ("BG16 SNL","Volkwagen","S-MAX","Blue");
INSERT INTO vehicle VALUES ("VW58 BRB","Renualt","Transit Custom","Silver");
INSERT INTO vehicle VALUES ("PV61 FYV","Vauxhall","Transit Courier Kombi","Yellow");
INSERT INTO vehicle VALUES ("WC19 RGM","Skoda","Mustang Mach-E","Blue");
INSERT INTO vehicle VALUES ("DS11 OAB","Volkwagen","EcoSport","Yellow");
INSERT INTO vehicle VALUES ("GD67 DGC","Hyundai","Galaxy","Black");
INSERT INTO vehicle VALUES ("SR53 BFS","Honda","Fiesta","Green");
INSERT INTO vehicle VALUES ("RK52 ABA","Hyundai","Maverick","Green");
INSERT INTO vehicle VALUES ("LK12 GGA","Honda","Granada","Blue");
INSERT INTO vehicle VALUES ("EA57 NLO","Volkwagen","Granada","Blue");
INSERT INTO vehicle VALUES ("BA03 MDR","Vauxhall","Sierra","Red");
INSERT INTO vehicle VALUES ("HP05 WEB","Honda","Ka","Red");
INSERT INTO vehicle VALUES ("BH68 SLD","Volkwagen","Focus C-MAX","Blue");
INSERT INTO vehicle VALUES ("RN06 NEF","Toyota","Sierra","White");
INSERT INTO vehicle VALUES ("ON58 OFK","Volkwagen","Focus","Blue");
INSERT INTO vehicle VALUES ("FV17 ERD","Skoda","Granada","Black");
INSERT INTO vehicle VALUES ("CV06 MLM","Skoda","Scorpio","Red");
INSERT INTO vehicle VALUES ("RF56 SER","Volkwagen","Focus","White");
INSERT INTO vehicle VALUES ("HM20 YHM","Renualt","B-MAX","Green");
INSERT INTO vehicle VALUES ("NE60 SVW","Nissan","Kuga","White");
INSERT INTO vehicle VALUES ("FF04 YAC","Vauxhall","C-MAX","Silver");
INSERT INTO vehicle VALUES ("ME14 CGH","Ford","Grand C-MAX","Silver");
INSERT INTO vehicle VALUES ("VO09 OHO","Nissan","B-MAX","Red");
INSERT INTO vehicle VALUES ("MA02 YDP","Toyota","Cougar","Red");
INSERT INTO vehicle VALUES ("HE06 MFE","Skoda","Cougar","Red");
INSERT INTO vehicle VALUES ("WS03 NLB","Nissan","Explorer","Green");
INSERT INTO vehicle VALUES ("AP12 EBW","Nissan","Scorpio","Black");
INSERT INTO vehicle VALUES ("CV67 SAE","Vauxhall","Cougar","Red");
INSERT INTO vehicle VALUES ("NM60 LKA","Vauxhall","S-MAX","White");
INSERT INTO vehicle VALUES ("DS66 SVA","Renualt","Maverick","Green");
INSERT INTO vehicle VALUES ("HH05 SNC","Honda","Focus","Blue");
INSERT INTO vehicle VALUES ("BG08 DRM","Skoda","Maverick","Blue");
INSERT INTO vehicle VALUES ("CO08 BHN","Nissan","C-MAX","Blue");
INSERT INTO vehicle VALUES ("CG03 KWS","Kia","Orion","Yellow");
INSERT INTO vehicle VALUES ("FW54 OPL","Kia","C-MAX","Red");
INSERT INTO vehicle VALUES ("NL16 MFS","Nissan","Edge","Red");
INSERT INTO vehicle VALUES ("KR60 VWC","Vauxhall","Orion","Black");
INSERT INTO vehicle VALUES ("OS14 CYC","Nissan","Edge","Red");
INSERT INTO vehicle VALUES ("RS09 NPG","Volkwagen","Escort","Blue");
INSERT INTO vehicle VALUES ("PN53 EBN","Skoda","Mustang Mach-E","Yellow");
INSERT INTO vehicle VALUES ("AR16 LWE","Toyota","Scorpio","Silver");
INSERT INTO vehicle VALUES ("AE20 VPS","Hyundai","Puma","Yellow");
INSERT INTO vehicle VALUES ("KR15 NAF","Skoda","Mustang","Black");
INSERT INTO vehicle VALUES ("KE07 NYC","Ford","Mondeo","Green");
INSERT INTO vehicle VALUES ("PD18 OPS","Honda","Fusion","Yellow");
INSERT INTO vehicle VALUES ("BK08 DFK","Kia","Ka","Silver");
INSERT INTO vehicle VALUES ("FF04 GLF","Vauxhall","Transit Courier Kombi","Blue");
INSERT INTO vehicle VALUES ("VR17 MBR","Vauxhall","Galaxy","Red");
INSERT INTO vehicle VALUES ("KV54 EPR","Renualt","Mustang Mach-E","Blue");
INSERT INTO vehicle VALUES ("MS11 DGV","Kia","Tourneo Courier","Red");
INSERT INTO vehicle VALUES ("RO70 RNG","Toyota","Capri","Yellow");
INSERT INTO vehicle VALUES ("GK03 NYD","Honda","Maverick","Silver");
INSERT INTO vehicle VALUES ("PF19 NMW","Vauxhall","Tourneo Connect","White");
INSERT INTO vehicle VALUES ("BE20 BNM","Kia","Sierra","Black");
INSERT INTO vehicle VALUES ("NS70 DLS","Honda","B-MAX","Blue");
INSERT INTO vehicle VALUES ("GP12 BPB","Ford","Maverick","Blue");
INSERT INTO vehicle VALUES ("YD17 DCM","Volkwagen","Ka","Green");
INSERT INTO vehicle VALUES ("KL03 LDE","Honda","S-MAX","Red");
INSERT INTO vehicle VALUES ("GP08 HMR","Renualt","S-MAX","Blue");
INSERT INTO vehicle VALUES ("VL66 RSE","Skoda","EcoSport","Blue");
INSERT INTO vehicle VALUES ("LP11 KML","Skoda","Cougar","White");
INSERT INTO vehicle VALUES ("LK20 AFS","Volkwagen","Grand Tourneo Connect","White");
INSERT INTO vehicle VALUES ("NR17 EGC","Volkwagen","Tourneo Courier","Red");
INSERT INTO vehicle VALUES ("WC70 KOK","Hyundai","Focus","Silver");
INSERT INTO vehicle VALUES ("VL65 OSV","Kia","Puma","Blue");
INSERT INTO vehicle VALUES ("KW55 LWE","Toyota","Probe","Green");
INSERT INTO vehicle VALUES ("PD58 BYD","Ford","Fusion","Silver");
INSERT INTO vehicle VALUES ("KK65 EYS","Kia","Grand C-MAX","Blue");
INSERT INTO vehicle VALUES ("NV15 EDY","Skoda","Explorer","Blue");
INSERT INTO vehicle VALUES ("HC14 EBC","Renualt","Transit Custom","Green");
INSERT INTO vehicle VALUES ("SB69 HNV","Renualt","S-MAX","Black");
