CREATE TABLE Vehicle (
    vehReg VARCHAR(8),
    make VARCHAR(20),
    model VARCHAR(20),
    colour VARCHAR(20),
    PRIMARY KEY (vehReg)
    );

INSERT INTO vehicle VALUES ("PO61 FRY","Kia","EcoSport","Yellow");
INSERT INTO vehicle VALUES ("SY11 PSS","Renualt","Puma","Silver");
INSERT INTO vehicle VALUES ("OV13 BRP","Volkwagen","Sierra","Black");
INSERT INTO vehicle VALUES ("SE65 KOL","Honda","Focus C-MAX","Red");
INSERT INTO vehicle VALUES ("GO60 YLY","Skoda","Cougar","Silver");
INSERT INTO vehicle VALUES ("VS16 BLE","Volkwagen","Tourneo Courier","Black");
INSERT INTO vehicle VALUES ("YS70 CLS","Nissan","Grand Tourneo Connect","Yellow");
INSERT INTO vehicle VALUES ("LN12 EWA","Volkwagen","C-MAX","Black");
INSERT INTO vehicle VALUES ("KW67 BMM","Vauxhall","Tourneo Courier","Silver");
INSERT INTO vehicle VALUES ("YC67 CLD","Toyota","Focus C-MAX","Silver");
INSERT INTO vehicle VALUES ("GH55 VDS","Skoda","S-MAX","Yellow");
INSERT INTO vehicle VALUES ("HV54 WFC","Hyundai","Scorpio","Yellow");
INSERT INTO vehicle VALUES ("CY58 FEV","Honda","Cougar","Green");
INSERT INTO vehicle VALUES ("VP67 NVP","Hyundai","Cougar","White");
INSERT INTO vehicle VALUES ("WF10 BNS","Nissan","Ka","Silver");
INSERT INTO vehicle VALUES ("CW60 NWY","Nissan","Kuga","Black");
INSERT INTO vehicle VALUES ("KW09 NOA","Skoda","Explorer","Green");
INSERT INTO vehicle VALUES ("VP64 LYW","Toyota","Fiesta","Red");
INSERT INTO vehicle VALUES ("PS09 VCE","Kia","Galaxy","Yellow");
INSERT INTO vehicle VALUES ("FW69 GNP","Hyundai","Puma","Silver");
INSERT INTO vehicle VALUES ("HV61 YPL","Vauxhall","Fiesta","White");
INSERT INTO vehicle VALUES ("BA02 LOS","Vauxhall","Puma","Silver");
INSERT INTO vehicle VALUES ("SO10 GAG","Volkwagen","Edge","Black");
INSERT INTO vehicle VALUES ("SW55 PKK","Honda","Focus","White");
INSERT INTO vehicle VALUES ("RB56 BYO","Hyundai","Ka","White");
INSERT INTO vehicle VALUES ("SW12 GCC","Skoda","Granada","Yellow");
INSERT INTO vehicle VALUES ("GS18 OYR","Nissan","Grand Tourneo Connect","Black");
INSERT INTO vehicle VALUES ("LA62 SMO","Nissan","EcoSport","Blue");
INSERT INTO vehicle VALUES ("DW19 FYN","Nissan","Fiesta","Yellow");
INSERT INTO vehicle VALUES ("KW66 VOP","Renualt","Escort","Black");
INSERT INTO vehicle VALUES ("WS70 KKF","Nissan","Mondeo","Blue");
INSERT INTO vehicle VALUES ("NA57 MKR","Volkwagen","Orion","Blue");
INSERT INTO vehicle VALUES ("GM13 OCE","Renualt","Tourneo Connect","Black");
INSERT INTO vehicle VALUES ("NW05 HNB","Toyota","Cougar","Blue");
INSERT INTO vehicle VALUES ("HL03 ESG","Nissan","Galaxy","White");
INSERT INTO vehicle VALUES ("HN19 MKD","Renualt","Sierra Sapphire","Yellow");
INSERT INTO vehicle VALUES ("AM64 NFY","Ford","Mustang Mach-E","Yellow");
INSERT INTO vehicle VALUES ("CF12 DER","Kia","Galaxy","Silver");
INSERT INTO vehicle VALUES ("YR03 EHW","Ford","Capri","Blue");
INSERT INTO vehicle VALUES ("BF08 SMM","Volkwagen","Edge","Yellow");
INSERT INTO vehicle VALUES ("YO64 DNS","Renualt","B-MAX","White");
INSERT INTO vehicle VALUES ("HV09 FAR","Nissan","Sierra","Silver");
INSERT INTO vehicle VALUES ("GF58 WGY","Nissan","Sierra Sapphire","Yellow");
INSERT INTO vehicle VALUES ("FB05 VWA","Volkwagen","Transit Custom","Blue");
INSERT INTO vehicle VALUES ("NN62 EHY","Ford","B-MAX","Blue");
INSERT INTO vehicle VALUES ("CH59 FFR","Renualt","Tourneo Courier","Green");
INSERT INTO vehicle VALUES ("FF58 RBA","Vauxhall","Galaxy","Silver");
INSERT INTO vehicle VALUES ("AK61 GKL","Honda","B-MAX","Yellow");
INSERT INTO vehicle VALUES ("YP10 FDM","Skoda","Grand C-MAX","Green");
INSERT INTO vehicle VALUES ("RD13 ASC","Toyota","Granada","White");
INSERT INTO vehicle VALUES ("KC63 SVV","Skoda","B-MAX","White");
INSERT INTO vehicle VALUES ("CK66 YFY","Kia","Transit Custom","Red");
INSERT INTO vehicle VALUES ("PD03 NHO","Toyota","Mustang Mach-E","Silver");
INSERT INTO vehicle VALUES ("VR03 WNP","Ford","Grand C-MAX","Red");
INSERT INTO vehicle VALUES ("WG03 MLD","Toyota","C-MAX","Blue");
INSERT INTO vehicle VALUES ("RV10 KMA","Ford","Galaxy","Yellow");
INSERT INTO vehicle VALUES ("GC17 CRN","Toyota","Granada","Yellow");
INSERT INTO vehicle VALUES ("KB59 KDG","Ford","Focus C-MAX","Black");
INSERT INTO vehicle VALUES ("HC67 FAL","Vauxhall","Escort","Black");
INSERT INTO vehicle VALUES ("FB07 OOE","Hyundai","Tourneo Connect","Blue");
INSERT INTO vehicle VALUES ("RO52 OSK","Renualt","S-MAX","Black");
INSERT INTO vehicle VALUES ("HW70 YKS","Ford","StreetKa","Silver");
INSERT INTO vehicle VALUES ("HG69 WMG","Nissan","Tourneo Courier","Yellow");
INSERT INTO vehicle VALUES ("WS65 OSN","Toyota","Fiesta","Yellow");
INSERT INTO vehicle VALUES ("BM59 EBA","Volkwagen","Grand Tourneo Connect","Black");
INSERT INTO vehicle VALUES ("CK58 MYS","Hyundai","Probe","White");
INSERT INTO vehicle VALUES ("AK53 OYL","Vauxhall","Fusion","Blue");
INSERT INTO vehicle VALUES ("SO62 GRW","Renualt","EcoSport","Silver");
INSERT INTO vehicle VALUES ("RK04 WDP","Volkwagen","Sierra Sapphire","White");
INSERT INTO vehicle VALUES ("BB05 OWB","Hyundai","Orion","Black");
INSERT INTO vehicle VALUES ("VF62 MGH","Nissan","StreetKa","Red");
INSERT INTO vehicle VALUES ("KW55 KAV","Vauxhall","StreetKa","White");
INSERT INTO vehicle VALUES ("FA62 BAK","Ford","Capri","Black");
INSERT INTO vehicle VALUES ("ER68 VMO","Volkwagen","Mondeo","Silver");
INSERT INTO vehicle VALUES ("FA68 MCF","Toyota","Edge","Silver");
INSERT INTO vehicle VALUES ("HC61 GCD","Hyundai","Transit Custom","Silver");
INSERT INTO vehicle VALUES ("BH63 GEB","Honda","C-MAX","White");
INSERT INTO vehicle VALUES ("RR66 CRB","Hyundai","Orion","Yellow");
INSERT INTO vehicle VALUES ("BF18 OCD","Nissan","Granada","Yellow");
INSERT INTO vehicle VALUES ("OS03 FPA","Kia","Maverick","Red");
INSERT INTO vehicle VALUES ("VD16 SVW","Skoda","Focus C-MAX","Yellow");
INSERT INTO vehicle VALUES ("NP67 OHA","Skoda","Grand Tourneo Connect","Blue");
INSERT INTO vehicle VALUES ("PF14 GEY","Honda","Capri","Black");
INSERT INTO vehicle VALUES ("DH69 CNV","Renualt","Tourneo Connect","Black");
INSERT INTO vehicle VALUES ("MN03 DKB","Hyundai","S-MAX","Yellow");
INSERT INTO vehicle VALUES ("HA68 RMH","Renualt","C-MAX","Silver");
INSERT INTO vehicle VALUES ("KY66 MLD","Nissan","Mustang Mach-E","Silver");
INSERT INTO vehicle VALUES ("PK14 KAY","Volkwagen","Puma","Blue");
INSERT INTO vehicle VALUES ("WP66 RKE","Honda","Explorer","White");
INSERT INTO vehicle VALUES ("WO52 PAK","Volkwagen","C-MAX","Red");
INSERT INTO vehicle VALUES ("DA52 WYV","Kia","EcoSport","Yellow");
INSERT INTO vehicle VALUES ("DO04 EER","Hyundai","Sierra Sapphire","Black");
INSERT INTO vehicle VALUES ("DA59 SAC","Renualt","Granada","Silver");
INSERT INTO vehicle VALUES ("KY06 DKA","Skoda","Puma","White");
INSERT INTO vehicle VALUES ("FG53 FWC","Honda","Probe","Green");
INSERT INTO vehicle VALUES ("SL65 PMO","Renualt","Transit Courier Kombi","Silver");
INSERT INTO vehicle VALUES ("AE10 GOR","Toyota","S-MAX","Yellow");
INSERT INTO vehicle VALUES ("ML63 KNL","Honda","Transit Courier Kombi","Blue");
INSERT INTO vehicle VALUES ("NM67 HAR","Hyundai","Capri","White");
INSERT INTO vehicle VALUES ("KO13 WVN","Vauxhall","Fusion","White");
INSERT INTO vehicle VALUES ("EO19 SEH","Kia","Focus","Blue");
INSERT INTO vehicle VALUES ("FH54 MDW","Vauxhall","Tourneo Connect","Silver");
INSERT INTO vehicle VALUES ("FG55 KWM","Kia","S-MAX","Red");
INSERT INTO vehicle VALUES ("PN66 DVE","Hyundai","Orion","Silver");
INSERT INTO vehicle VALUES ("CM18 YGV","Hyundai","Mondeo","Silver");
INSERT INTO vehicle VALUES ("FL55 RHP","Vauxhall","Focus C-MAX","Blue");
INSERT INTO vehicle VALUES ("DV61 VYM","Honda","Scorpio","Yellow");
INSERT INTO vehicle VALUES ("HB04 EEV","Skoda","Sierra Sapphire","White");
INSERT INTO vehicle VALUES ("BY63 BMA","Ford","StreetKa","Yellow");
INSERT INTO vehicle VALUES ("WS02 DLH","Kia","Transit Custom","Silver");
INSERT INTO vehicle VALUES ("DE63 YOF","Skoda","Mustang Mach-E","Blue");
INSERT INTO vehicle VALUES ("DR56 OMD","Kia","Sierra","Red");
INSERT INTO vehicle VALUES ("SS59 LFF","Nissan","Focus C-MAX","Yellow");
INSERT INTO vehicle VALUES ("HV16 CDM","Nissan","Edge","Silver");
INSERT INTO vehicle VALUES ("FG19 VVG","Nissan","Probe","Black");
INSERT INTO vehicle VALUES ("AA02 MLM","Renualt","Focus C-MAX","Blue");
INSERT INTO vehicle VALUES ("WW53 MNE","Nissan","Kuga","Red");
INSERT INTO vehicle VALUES ("RN06 SAE","Volkwagen","Grand Tourneo Connect","White");
INSERT INTO vehicle VALUES ("WG13 MBA","Hyundai","Puma","Blue");
INSERT INTO vehicle VALUES ("GB68 NPY","Hyundai","Sierra","Silver");
INSERT INTO vehicle VALUES ("FL13 CON","Vauxhall","Granada","White");
INSERT INTO vehicle VALUES ("AR12 DKF","Nissan","Tourneo Connect","Silver");
INSERT INTO vehicle VALUES ("PF65 AWS","Ford","Focus C-MAX","Black");
INSERT INTO vehicle VALUES ("FR67 HGH","Kia","Mustang","Silver");
INSERT INTO vehicle VALUES ("MR18 PFD","Ford","EcoSport","Yellow");
INSERT INTO vehicle VALUES ("CB54 OBP","Kia","Capri","Blue");
INSERT INTO vehicle VALUES ("NM57 YHK","Volkwagen","Cougar","Yellow");
INSERT INTO vehicle VALUES ("FW03 SGG","Kia","Galaxy","Blue");
INSERT INTO vehicle VALUES ("PN08 KCN","Skoda","Mondeo","Green");
INSERT INTO vehicle VALUES ("SP70 ARR","Volkwagen","Tourneo Courier","Silver");
INSERT INTO vehicle VALUES ("MO59 WYE","Hyundai","Maverick","Yellow");
INSERT INTO vehicle VALUES ("PD19 GVP","Honda","Escort","White");
INSERT INTO vehicle VALUES ("SF60 MAD","Ford","Cougar","White");
INSERT INTO vehicle VALUES ("LM62 GON","Nissan","Sierra Sapphire","Black");
INSERT INTO vehicle VALUES ("HC61 COO","Skoda","Maverick","Red");
INSERT INTO vehicle VALUES ("RB62 ACO","Hyundai","Capri","Silver");
INSERT INTO vehicle VALUES ("LS06 KVF","Vauxhall","Focus","Blue");
INSERT INTO vehicle VALUES ("DO63 HAE","Hyundai","Capri","Black");
INSERT INTO vehicle VALUES ("HD66 HWH","Skoda","Grand C-MAX","Black");
INSERT INTO vehicle VALUES ("CL57 SDM","Toyota","Focus","White");
INSERT INTO vehicle VALUES ("WR05 KMH","Renualt","Ka","Yellow");
INSERT INTO vehicle VALUES ("AC08 OAM","Ford","C-MAX","Yellow");
INSERT INTO vehicle VALUES ("VS58 RBG","Hyundai","Grand Tourneo Connect","Blue");
INSERT INTO vehicle VALUES ("BB57 VSV","Toyota","StreetKa","Yellow");
INSERT INTO vehicle VALUES ("AK61 YKD","Vauxhall","EcoSport","Green");
INSERT INTO vehicle VALUES ("AE03 PDV","Volkwagen","Grand Tourneo Connect","Yellow");
INSERT INTO vehicle VALUES ("EE58 HRB","Ford","Capri","Yellow");
INSERT INTO vehicle VALUES ("PB57 NLG","Volkwagen","Granada","Yellow");
INSERT INTO vehicle VALUES ("CO11 KSV","Nissan","Grand Tourneo Connect","Red");
INSERT INTO vehicle VALUES ("FY63 GCF","Ford","Mondeo","Red");
INSERT INTO vehicle VALUES ("CF68 PMG","Renualt","Cougar","White");
INSERT INTO vehicle VALUES ("DM53 HLD","Volkwagen","Mondeo","White");
INSERT INTO vehicle VALUES ("KS09 SAF","Honda","Kuga","White");
INSERT INTO vehicle VALUES ("AG70 OOC","Kia","Scorpio","Blue");
INSERT INTO vehicle VALUES ("PW53 FLB","Renualt","Mustang","Yellow");
INSERT INTO vehicle VALUES ("SK67 MER","Vauxhall","Capri","Red");
INSERT INTO vehicle VALUES ("DB10 DGL","Nissan","B-MAX","Yellow");
INSERT INTO vehicle VALUES ("CM54 PEP","Toyota","Escort","Silver");
INSERT INTO vehicle VALUES ("OC57 ROH","Vauxhall","Granada","Blue");
INSERT INTO vehicle VALUES ("WA20 AND","Hyundai","Fiesta","Red");
INSERT INTO vehicle VALUES ("CH17 BGB","Kia","Granada","Green");
INSERT INTO vehicle VALUES ("KO06 EFM","Toyota","Galaxy","White");
INSERT INTO vehicle VALUES ("OL56 OYA","Hyundai","Ka","Blue");
INSERT INTO vehicle VALUES ("KR59 KYR","Hyundai","Focus C-MAX","Blue");
INSERT INTO vehicle VALUES ("KM18 AMY","Toyota","Explorer","Green");
INSERT INTO vehicle VALUES ("CO05 WRW","Vauxhall","Granada","Red");
INSERT INTO vehicle VALUES ("KE55 PNC","Vauxhall","Transit Courier Kombi","Yellow");
INSERT INTO vehicle VALUES ("EP02 NYO","Nissan","Mustang Mach-E","Yellow");
INSERT INTO vehicle VALUES ("FS56 KWV","Skoda","Tourneo Courier","Black");
INSERT INTO vehicle VALUES ("YS10 YFF","Volkwagen","Mustang","Silver");
INSERT INTO vehicle VALUES ("LG57 ALM","Renualt","Cougar","Silver");
INSERT INTO vehicle VALUES ("LW18 YHA","Ford","Puma","Black");
INSERT INTO vehicle VALUES ("GE68 MLC","Renualt","Focus C-MAX","White");
INSERT INTO vehicle VALUES ("OF60 HCN","Nissan","Mondeo","White");
INSERT INTO vehicle VALUES ("RA54 MPE","Toyota","Orion","Red");
INSERT INTO vehicle VALUES ("RY12 OLW","Renualt","Galaxy","Blue");
INSERT INTO vehicle VALUES ("VD04 BHS","Vauxhall","Puma","Red");
INSERT INTO vehicle VALUES ("OH52 OAL","Skoda","Escort","Blue");
INSERT INTO vehicle VALUES ("SN20 EPE","Vauxhall","Mondeo","Green");
INSERT INTO vehicle VALUES ("KM12 DWN","Hyundai","Focus","Red");
INSERT INTO vehicle VALUES ("DH02 CNR","Kia","Probe","Silver");
INSERT INTO vehicle VALUES ("BE13 WVN","Hyundai","Orion","Green");
INSERT INTO vehicle VALUES ("CO68 CHG","Ford","B-MAX","White");
INSERT INTO vehicle VALUES ("VK05 LML","Renualt","Probe","Black");
INSERT INTO vehicle VALUES ("LV64 OAP","Renualt","Fiesta","Silver");
INSERT INTO vehicle VALUES ("MP17 RVP","Hyundai","Granada","Red");
INSERT INTO vehicle VALUES ("RV10 FOL","Skoda","Capri","Yellow");
INSERT INTO vehicle VALUES ("YF61 LSK","Nissan","EcoSport","White");
INSERT INTO vehicle VALUES ("LC67 VED","Volkwagen","Capri","Red");
INSERT INTO vehicle VALUES ("LO05 PAF","Vauxhall","Galaxy","Yellow");
INSERT INTO vehicle VALUES ("RF69 GBE","Nissan","Grand Tourneo Connect","Blue");
INSERT INTO vehicle VALUES ("FY19 RRK","Hyundai","Probe","Yellow");
INSERT INTO vehicle VALUES ("OW08 LCR","Skoda","Orion","White");
INSERT INTO vehicle VALUES ("DO60 YDG","Toyota","Mondeo","White");
INSERT INTO vehicle VALUES ("GK14 MWC","Ford","Grand Tourneo Connect","Silver");
INSERT INTO vehicle VALUES ("DF16 PLW","Skoda","Kuga","White");
INSERT INTO vehicle VALUES ("PF18 MAP","Vauxhall","Focus C-MAX","Black");
INSERT INTO vehicle VALUES ("RF13 BNR","Hyundai","Scorpio","Red");
INSERT INTO vehicle VALUES ("SH67 HNC","Vauxhall","Cougar","Silver");
INSERT INTO vehicle VALUES ("HD62 NHE","Ford","Orion","Blue");
