title: Computing Science
description: Focusing on SQA's qualifications.

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - H-CS-SDD.md
  
theme: jekyll-theme-minimal

markdown: kramdown
