title: Computing Science
description: Focusing on SQA's qualifications.

# theme: jekyll-theme-minimal
theme: just-the-docs

url: https://mrfriendcs.github.io/YOUR-SITE-NAME

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - N5-CS-DDD.md
  - N5-CS-SDD.md
  - N5-CS-WDD.md
  - H-CS-DDD.md
  - H-CS-SDD.md
  
markdown: kramdown
