CREATE TABLE Teacher (
    staffID INT NOT NULL,
    subjectID INT NOT NULL,
    PRIMARY KEY (staffID, subjectID),
    FOREIGN KEY (staffID)
        REFERENCES Staff (staffID),
    FOREIGN KEY (subjectID)
        REFERENCES Subject (subjectID)
);

INSERT INTO Teacher VALUES 1,5);
INSERT INTO Teacher VALUES 2,5);
INSERT INTO Teacher VALUES 3,7);
INSERT INTO Teacher VALUES 4,12);
INSERT INTO Teacher VALUES 7,1);
INSERT INTO Teacher VALUES 8,11);
INSERT INTO Teacher VALUES 9,1);
INSERT INTO Teacher VALUES 10,4);
INSERT INTO Teacher VALUES 11,12);
INSERT INTO Teacher VALUES 12,7);
INSERT INTO Teacher VALUES 13,3);
INSERT INTO Teacher VALUES 14,13);
INSERT INTO Teacher VALUES 17,3);
INSERT INTO Teacher VALUES 18,14);
INSERT INTO Teacher VALUES 19,4);
INSERT INTO Teacher VALUES 20,8);
INSERT INTO Teacher VALUES 21,1);
INSERT INTO Teacher VALUES 22,8);
INSERT INTO Teacher VALUES 23,12);
INSERT INTO Teacher VALUES 24,10);
INSERT INTO Teacher VALUES 27,8);
INSERT INTO Teacher VALUES 28,1);
INSERT INTO Teacher VALUES 31,11);
INSERT INTO Teacher VALUES 33,13);
INSERT INTO Teacher VALUES 34,10);
INSERT INTO Teacher VALUES 36,12);
INSERT INTO Teacher VALUES 37,8);
INSERT INTO Teacher VALUES 38,12);
INSERT INTO Teacher VALUES 39,7);
INSERT INTO Teacher VALUES 40,15);
INSERT INTO Teacher VALUES 43,3);
INSERT INTO Teacher VALUES 44,12);
INSERT INTO Teacher VALUES 45,13);
INSERT INTO Teacher VALUES 46,3);
INSERT INTO Teacher VALUES 48,10);
INSERT INTO Teacher VALUES 50,3);
INSERT INTO Teacher VALUES 50,2);
INSERT INTO Teacher VALUES 51,10);
INSERT INTO Teacher VALUES 52,7);
INSERT INTO Teacher VALUES 53,4);
INSERT INTO Teacher VALUES 54,10);
INSERT INTO Teacher VALUES 55,9);
INSERT INTO Teacher VALUES 57,12);
INSERT INTO Teacher VALUES 57,9);
INSERT INTO Teacher VALUES 58,14);
INSERT INTO Teacher VALUES 59,11);
INSERT INTO Teacher VALUES 60,1);
INSERT INTO Teacher VALUES 61,11);
INSERT INTO Teacher VALUES 63,12);
INSERT INTO Teacher VALUES 64,3);
INSERT INTO Teacher VALUES 64,2);
INSERT INTO Teacher VALUES 66,15);
INSERT INTO Teacher VALUES 67,1);
INSERT INTO Teacher VALUES 69,5);
INSERT INTO Teacher VALUES 70,3);
INSERT INTO Teacher VALUES 71,13);
INSERT INTO Teacher VALUES 72,8);
INSERT INTO Teacher VALUES 74,15);
INSERT INTO Teacher VALUES 75,10);
INSERT INTO Teacher VALUES 75,6);
INSERT INTO Teacher VALUES 76,4);
INSERT INTO Teacher VALUES 77,7);
INSERT INTO Teacher VALUES 78,12);
INSERT INTO Teacher VALUES 79,9);
INSERT INTO Teacher VALUES 80,13);
INSERT INTO Teacher VALUES 81,13);
INSERT INTO Teacher VALUES 82,9);
INSERT INTO Teacher VALUES 83,12);
INSERT INTO Teacher VALUES 84,12);
INSERT INTO Teacher VALUES 84,5);
INSERT INTO Teacher VALUES 85,12);
INSERT INTO Teacher VALUES 86,12);
INSERT INTO Teacher VALUES 87,13);
INSERT INTO Teacher VALUES 89,3);
INSERT INTO Teacher VALUES 90,7);
INSERT INTO Teacher VALUES 91,1);
INSERT INTO Teacher VALUES 92,3);
INSERT INTO Teacher VALUES 92,2);
INSERT INTO Teacher VALUES 93,7);
INSERT INTO Teacher VALUES 94,13);
INSERT INTO Teacher VALUES 96,4);
INSERT INTO Teacher VALUES 97,10);
INSERT INTO Teacher VALUES 98,3);
INSERT INTO Teacher VALUES 98,2);
