CREATE TABLE Gift (
    giftID INT NOT NULL,
    childID INT,
    item VARCHAR(50),
    PRIMARY KEY (giftID),
    FOREIGN KEY (childID)
        REFERENCES child(childID)
);

INSERT INTO Gift VALUES (1,6,"Teenage Mutant Ninja Turtles Pizza Delivery Van");
INSERT INTO Gift VALUES (2,78,"Chad Valley Wooden Pizza");
INSERT INTO Gift VALUES (3,109,"LEGO Harry Potter Dobby the House-Elf Figure");
INSERT INTO Gift VALUES (4,195,"LEGO Technic Lamborghini");
INSERT INTO Gift VALUES (5,138,"Gabby's Dollhouse Cat Friendship Cruise Ship Playset");
INSERT INTO Gift VALUES (6,89,"Hot Wheels Monster Trucks Ultimate Crush Yard Playset");
INSERT INTO Gift VALUES (7,49,"Chad Valley Wooden Pizza");
INSERT INTO Gift VALUES (8,146,"Nerf Elite 2.0 Double Punch Blaster");
INSERT INTO Gift VALUES (9,119,"Barbie Estate Dolls House and 3 Dolls");
INSERT INTO Gift VALUES (10,138,"Teenage Mutant Ninja Turtles Pizza Delivery Van");
INSERT INTO Gift VALUES (11,11,"Fingerlings Monkey Pink - Harmony");
INSERT INTO Gift VALUES (12,16,"Squishmallows Drew the Mint Dragon");
INSERT INTO Gift VALUES (13,120,"Teenage Mutant Ninja Turtles Pizza Delivery Van");
INSERT INTO Gift VALUES (14,99,"Furby Purple Interactive Toy Plush");
INSERT INTO Gift VALUES (15,96,"Furby Purple Interactive Toy Plush");
INSERT INTO Gift VALUES (16,30,"DesignaFriend Connie Fashion Designer Doll");
INSERT INTO Gift VALUES (17,56,"LEGO Harry Potter Dobby the House-Elf Figure");
INSERT INTO Gift VALUES (18,133,"MGA's Miniverse – Make it Mini Food: Dine");
INSERT INTO Gift VALUES (19,44,"Little Live Pets – My Puppy’s Home Dalmatian Edition");
INSERT INTO Gift VALUES (20,184,"Barbie Estate Dolls House and 3 Dolls");
INSERT INTO Gift VALUES (21,138,"DesignaFriend Connie Fashion Designer Doll");
INSERT INTO Gift VALUES (22,90,"Bitzee Interactive Digital Pet");
INSERT INTO Gift VALUES (23,186,"LEGO Technic Lamborghini");
INSERT INTO Gift VALUES (24,12,"Chad Valley Wooden 2 in 1 Café");
INSERT INTO Gift VALUES (25,135,"Fingerlings Monkey Pink - Harmony");
INSERT INTO Gift VALUES (26,138,"LEGO Star WarsAhsoka Clone Trooper");
INSERT INTO Gift VALUES (27,111,"Chad Valley Wooden 2 in 1 Café");
INSERT INTO Gift VALUES (28,12,"Chad Valley Wooden 2 in 1 Café");
INSERT INTO Gift VALUES (29,7,"Nerf Elite 2.0 Double Punch Blaster");
INSERT INTO Gift VALUES (30,89,"Furby Purple Interactive Toy Plush");
INSERT INTO Gift VALUES (31,121,"Hot Wheels Monster Trucks Ultimate Crush Yard Playset");
INSERT INTO Gift VALUES (32,78,"Little Live Pets – My Puppy’s Home Dalmatian Edition");
INSERT INTO Gift VALUES (33,95,"Hot Wheels Monster Trucks Ultimate Crush Yard Playset");
INSERT INTO Gift VALUES (34,77,"Chad Valley Trevor Talk Back Dino");
INSERT INTO Gift VALUES (35,107,"Hot Wheels Monster Trucks Ultimate Crush Yard Playset");
INSERT INTO Gift VALUES (36,59,"LEGO Technic Lamborghini");
INSERT INTO Gift VALUES (37,84,"MGA's Miniverse – Make it Mini Food: Dine");
INSERT INTO Gift VALUES (38,41,"Fingerlings Monkey Pink - Harmony");
INSERT INTO Gift VALUES (39,36,"Squishmallows Drew the Mint Dragon");
INSERT INTO Gift VALUES (40,136,"Nerf Elite 2.0 Double Punch Blaster");
INSERT INTO Gift VALUES (41,112,"Little Live Pets – My Puppy’s Home Dalmatian Edition");
INSERT INTO Gift VALUES (42,185,"Nerf Elite 2.0 Double Punch Blaster");
INSERT INTO Gift VALUES (43,158,"Chad Valley Wooden Pizza");
INSERT INTO Gift VALUES (44,7,"Fingerlings Monkey Pink - Harmony");
INSERT INTO Gift VALUES (45,153,"Fingerlings Monkey Pink - Harmony");
INSERT INTO Gift VALUES (46,23,"LEGO Harry Potter Dobby the House-Elf Figure");
INSERT INTO Gift VALUES (47,197,"Chad Valley Wooden Pizza");
INSERT INTO Gift VALUES (48,133,"Beast Lab Core Line Shark Playset");
INSERT INTO Gift VALUES (49,189,"Furby Purple Interactive Toy Plush");
INSERT INTO Gift VALUES (50,42,"Hot Wheels Monster Trucks Ultimate Crush Yard Playset");
INSERT INTO Gift VALUES (51,71,"Chad Valley Wooden Pizza");
INSERT INTO Gift VALUES (52,9,"Barbie Estate Dolls House and 3 Dolls");
INSERT INTO Gift VALUES (53,61,"Bitzee Interactive Digital Pet");
INSERT INTO Gift VALUES (54,24,"Beast Lab Core Line Shark Playset");
INSERT INTO Gift VALUES (55,73,"Chad Valley Trevor Talk Back Dino");
INSERT INTO Gift VALUES (56,91,"Teenage Mutant Ninja Turtles Pizza Delivery Van");
INSERT INTO Gift VALUES (57,105,"Furby Purple Interactive Toy Plush");
INSERT INTO Gift VALUES (58,132,"Chad Valley Wooden 2 in 1 Café");
INSERT INTO Gift VALUES (59,155,"DesignaFriend Connie Fashion Designer Doll");
INSERT INTO Gift VALUES (60,170,"LEGO Harry Potter Dobby the House-Elf Figure");
INSERT INTO Gift VALUES (61,26,"Furby Purple Interactive Toy Plush");
INSERT INTO Gift VALUES (62,196,"DesignaFriend Connie Fashion Designer Doll");
INSERT INTO Gift VALUES (63,166,"Little Live Pets – My Puppy’s Home Dalmatian Edition");
INSERT INTO Gift VALUES (64,134,"LEGO Harry Potter Dobby the House-Elf Figure");
INSERT INTO Gift VALUES (65,150,"Bitzee Interactive Digital Pet");
INSERT INTO Gift VALUES (66,79,"DesignaFriend Connie Fashion Designer Doll");
INSERT INTO Gift VALUES (67,16,"DesignaFriend Connie Fashion Designer Doll");
INSERT INTO Gift VALUES (68,34,"Bitzee Interactive Digital Pet");
INSERT INTO Gift VALUES (69,127,"Teenage Mutant Ninja Turtles Pizza Delivery Van");
INSERT INTO Gift VALUES (70,99,"Hot Wheels Monster Trucks Ultimate Crush Yard Playset");
INSERT INTO Gift VALUES (71,178,"Hot Wheels Monster Trucks Ultimate Crush Yard Playset");
INSERT INTO Gift VALUES (72,94,"Chad Valley Trevor Talk Back Dino");
INSERT INTO Gift VALUES (73,35,"Squishmallows Drew the Mint Dragon");
INSERT INTO Gift VALUES (74,192,"DesignaFriend Connie Fashion Designer Doll");
INSERT INTO Gift VALUES (75,70,"Chad Valley Wooden 2 in 1 Café");
INSERT INTO Gift VALUES (76,57,"Chad Valley Wooden 2 in 1 Café");
INSERT INTO Gift VALUES (77,109,"Chad Valley Wooden 2 in 1 Café");
INSERT INTO Gift VALUES (78,104,"DesignaFriend Connie Fashion Designer Doll");
INSERT INTO Gift VALUES (79,134,"Little Live Pets – My Puppy’s Home Dalmatian Edition");
INSERT INTO Gift VALUES (80,7,"Fingerlings Monkey Pink - Harmony");
INSERT INTO Gift VALUES (81,187,"Gabby's Dollhouse Cat Friendship Cruise Ship Playset");
INSERT INTO Gift VALUES (82,57,"Hot Wheels Monster Trucks Ultimate Crush Yard Playset");
INSERT INTO Gift VALUES (83,97,"Chad Valley Wooden Pizza");
INSERT INTO Gift VALUES (84,198,"Nerf Elite 2.0 Double Punch Blaster");
INSERT INTO Gift VALUES (85,141,"LEGO Technic Lamborghini");
INSERT INTO Gift VALUES (86,1,"LEGO Star WarsAhsoka Clone Trooper");
INSERT INTO Gift VALUES (87,4,"Beast Lab Core Line Shark Playset");
INSERT INTO Gift VALUES (88,168,"MGA's Miniverse – Make it Mini Food: Dine");
INSERT INTO Gift VALUES (89,59,"Barbie Estate Dolls House and 3 Dolls");
INSERT INTO Gift VALUES (90,156,"Nerf Elite 2.0 Double Punch Blaster");
INSERT INTO Gift VALUES (91,174,"Fingerlings Monkey Pink - Harmony");
INSERT INTO Gift VALUES (92,176,"Barbie Estate Dolls House and 3 Dolls");
INSERT INTO Gift VALUES (93,144,"Barbie Estate Dolls House and 3 Dolls");
INSERT INTO Gift VALUES (94,100,"Chad Valley Trevor Talk Back Dino");
INSERT INTO Gift VALUES (95,86,"Barbie Estate Dolls House and 3 Dolls");
INSERT INTO Gift VALUES (96,143,"LEGO Technic Lamborghini");
INSERT INTO Gift VALUES (97,167,"LEGO Harry Potter Dobby the House-Elf Figure");
INSERT INTO Gift VALUES (98,93,"Furby Purple Interactive Toy Plush");
INSERT INTO Gift VALUES (99,82,"Fingerlings Monkey Pink - Harmony");
INSERT INTO Gift VALUES (100,63,"LEGO Technic Lamborghini");
INSERT INTO Gift VALUES (101,135,"Chad Valley Wooden 2 in 1 Café");
INSERT INTO Gift VALUES (102,195,"Little Live Pets – My Puppy’s Home Dalmatian Edition");
INSERT INTO Gift VALUES (103,84,"Barbie Estate Dolls House and 3 Dolls");
INSERT INTO Gift VALUES (104,5,"LEGO Technic Lamborghini");
INSERT INTO Gift VALUES (105,146,"Fingerlings Monkey Pink - Harmony");
INSERT INTO Gift VALUES (106,121,"Chad Valley Wooden 2 in 1 Café");
INSERT INTO Gift VALUES (107,28,"Hot Wheels Monster Trucks Ultimate Crush Yard Playset");
INSERT INTO Gift VALUES (108,110,"Little Live Pets – My Puppy’s Home Dalmatian Edition");
INSERT INTO Gift VALUES (109,53,"DesignaFriend Connie Fashion Designer Doll");
INSERT INTO Gift VALUES (110,147,"Fingerlings Monkey Pink - Harmony");
INSERT INTO Gift VALUES (111,18,"MGA's Miniverse – Make it Mini Food: Dine");
INSERT INTO Gift VALUES (112,97,"Chad Valley Wooden Pizza");
INSERT INTO Gift VALUES (113,167,"Chad Valley Trevor Talk Back Dino");
INSERT INTO Gift VALUES (114,30,"Hot Wheels Monster Trucks Ultimate Crush Yard Playset");
INSERT INTO Gift VALUES (115,98,"LEGO Star WarsAhsoka Clone Trooper");
INSERT INTO Gift VALUES (116,188,"LEGO Technic Lamborghini");
INSERT INTO Gift VALUES (117,86,"Bitzee Interactive Digital Pet");
INSERT INTO Gift VALUES (118,177,"Chad Valley Wooden 2 in 1 Café");
INSERT INTO Gift VALUES (119,30,"Barbie Estate Dolls House and 3 Dolls");
INSERT INTO Gift VALUES (120,56,"Barbie Estate Dolls House and 3 Dolls");
INSERT INTO Gift VALUES (121,142,"Chad Valley Trevor Talk Back Dino");
INSERT INTO Gift VALUES (122,176,"Barbie Estate Dolls House and 3 Dolls");
INSERT INTO Gift VALUES (123,33,"Hot Wheels Monster Trucks Ultimate Crush Yard Playset");
INSERT INTO Gift VALUES (124,97,"Chad Valley Wooden 2 in 1 Café");
INSERT INTO Gift VALUES (125,83,"LEGO Harry Potter Dobby the House-Elf Figure");
INSERT INTO Gift VALUES (126,148,"Beast Lab Core Line Shark Playset");
INSERT INTO Gift VALUES (127,62,"Teenage Mutant Ninja Turtles Pizza Delivery Van");
INSERT INTO Gift VALUES (128,135,"Fingerlings Monkey Pink - Harmony");
INSERT INTO Gift VALUES (129,162,"Bitzee Interactive Digital Pet");
INSERT INTO Gift VALUES (130,76,"Beast Lab Core Line Shark Playset");
INSERT INTO Gift VALUES (131,63,"Chad Valley Trevor Talk Back Dino");
INSERT INTO Gift VALUES (132,159,"Chad Valley Wooden 2 in 1 Café");
INSERT INTO Gift VALUES (133,107,"MGA's Miniverse – Make it Mini Food: Dine");
INSERT INTO Gift VALUES (134,11,"Fingerlings Monkey Pink - Harmony");
INSERT INTO Gift VALUES (135,47,"Furby Purple Interactive Toy Plush");
INSERT INTO Gift VALUES (136,23,"Bitzee Interactive Digital Pet");
INSERT INTO Gift VALUES (137,82,"LEGO Harry Potter Dobby the House-Elf Figure");
INSERT INTO Gift VALUES (138,28,"LEGO Technic Lamborghini");
INSERT INTO Gift VALUES (139,172,"Teenage Mutant Ninja Turtles Pizza Delivery Van");
INSERT INTO Gift VALUES (140,82,"Chad Valley Wooden 2 in 1 Café");
INSERT INTO Gift VALUES (141,31,"Squishmallows Drew the Mint Dragon");
INSERT INTO Gift VALUES (142,177,"Little Live Pets – My Puppy’s Home Dalmatian Edition");
INSERT INTO Gift VALUES (143,140,"Fingerlings Monkey Pink - Harmony");
INSERT INTO Gift VALUES (144,132,"DesignaFriend Connie Fashion Designer Doll");
INSERT INTO Gift VALUES (145,37,"LEGO Star WarsAhsoka Clone Trooper");
INSERT INTO Gift VALUES (146,54,"Beast Lab Core Line Shark Playset");
INSERT INTO Gift VALUES (147,142,"Chad Valley Wooden Pizza");
INSERT INTO Gift VALUES (148,177,"Bitzee Interactive Digital Pet");
INSERT INTO Gift VALUES (149,6,"Chad Valley Wooden Pizza");
INSERT INTO Gift VALUES (150,11,"MGA's Miniverse – Make it Mini Food: Dine");
INSERT INTO Gift VALUES (151,63,"Chad Valley Trevor Talk Back Dino");
INSERT INTO Gift VALUES (152,42,"Bitzee Interactive Digital Pet");
INSERT INTO Gift VALUES (153,154,"Little Live Pets – My Puppy’s Home Dalmatian Edition");
INSERT INTO Gift VALUES (154,7,"Chad Valley Trevor Talk Back Dino");
INSERT INTO Gift VALUES (155,71,"Teenage Mutant Ninja Turtles Pizza Delivery Van");
INSERT INTO Gift VALUES (156,100,"Fingerlings Monkey Pink - Harmony");
INSERT INTO Gift VALUES (157,155,"Gabby's Dollhouse Cat Friendship Cruise Ship Playset");
INSERT INTO Gift VALUES (158,109,"Little Live Pets – My Puppy’s Home Dalmatian Edition");
INSERT INTO Gift VALUES (159,173,"Bitzee Interactive Digital Pet");
INSERT INTO Gift VALUES (160,118,"Beast Lab Core Line Shark Playset");
INSERT INTO Gift VALUES (161,25,"Fingerlings Monkey Pink - Harmony");
INSERT INTO Gift VALUES (162,198,"Chad Valley Trevor Talk Back Dino");
INSERT INTO Gift VALUES (163,194,"Little Live Pets – My Puppy’s Home Dalmatian Edition");
INSERT INTO Gift VALUES (164,156,"LEGO Technic Lamborghini");
INSERT INTO Gift VALUES (165,108,"LEGO Star WarsAhsoka Clone Trooper");
INSERT INTO Gift VALUES (166,4,"Chad Valley Wooden 2 in 1 Café");
INSERT INTO Gift VALUES (167,20,"LEGO Harry Potter Dobby the House-Elf Figure");
INSERT INTO Gift VALUES (168,48,"LEGO Technic Lamborghini");
INSERT INTO Gift VALUES (169,59,"Gabby's Dollhouse Cat Friendship Cruise Ship Playset");
INSERT INTO Gift VALUES (170,79,"Chad Valley Wooden 2 in 1 Café");
INSERT INTO Gift VALUES (171,126,"Chad Valley Wooden Pizza");
INSERT INTO Gift VALUES (172,39,"Fingerlings Monkey Pink - Harmony");
INSERT INTO Gift VALUES (173,163,"MGA's Miniverse – Make it Mini Food: Dine");
INSERT INTO Gift VALUES (174,145,"Teenage Mutant Ninja Turtles Pizza Delivery Van");
INSERT INTO Gift VALUES (175,171,"Teenage Mutant Ninja Turtles Pizza Delivery Van");
INSERT INTO Gift VALUES (176,118,"DesignaFriend Connie Fashion Designer Doll");
INSERT INTO Gift VALUES (177,112,"Nerf Elite 2.0 Double Punch Blaster");
INSERT INTO Gift VALUES (178,27,"Fingerlings Monkey Pink - Harmony");
INSERT INTO Gift VALUES (179,100,"Fingerlings Monkey Pink - Harmony");
INSERT INTO Gift VALUES (180,95,"Nerf Elite 2.0 Double Punch Blaster");
INSERT INTO Gift VALUES (181,97,"Chad Valley Wooden 2 in 1 Café");
INSERT INTO Gift VALUES (182,76,"DesignaFriend Connie Fashion Designer Doll");
INSERT INTO Gift VALUES (183,177,"MGA's Miniverse – Make it Mini Food: Dine");
INSERT INTO Gift VALUES (184,133,"Squishmallows Drew the Mint Dragon");
INSERT INTO Gift VALUES (185,57,"Gabby's Dollhouse Cat Friendship Cruise Ship Playset");
INSERT INTO Gift VALUES (186,40,"Fingerlings Monkey Pink - Harmony");
INSERT INTO Gift VALUES (187,45,"Chad Valley Wooden Pizza");
INSERT INTO Gift VALUES (188,191,"Little Live Pets – My Puppy’s Home Dalmatian Edition");
INSERT INTO Gift VALUES (189,167,"MGA's Miniverse – Make it Mini Food: Dine");
INSERT INTO Gift VALUES (190,23,"LEGO Technic Lamborghini");
INSERT INTO Gift VALUES (191,119,"Chad Valley Wooden Pizza");
INSERT INTO Gift VALUES (192,72,"Teenage Mutant Ninja Turtles Pizza Delivery Van");
INSERT INTO Gift VALUES (193,104,"Squishmallows Drew the Mint Dragon");
INSERT INTO Gift VALUES (194,126,"Little Live Pets – My Puppy’s Home Dalmatian Edition");
INSERT INTO Gift VALUES (195,88,"LEGO Technic Lamborghini");
INSERT INTO Gift VALUES (196,194,"LEGO Star WarsAhsoka Clone Trooper");
INSERT INTO Gift VALUES (197,63,"Gabby's Dollhouse Cat Friendship Cruise Ship Playset");
INSERT INTO Gift VALUES (198,51,"Hot Wheels Monster Trucks Ultimate Crush Yard Playset");
INSERT INTO Gift VALUES (199,18,"Bitzee Interactive Digital Pet");
INSERT INTO Gift VALUES (200,176,"Squishmallows Drew the Mint Dragon");
INSERT INTO Gift VALUES (201,61,"Squishmallows Drew the Mint Dragon");
INSERT INTO Gift VALUES (202,28,"LEGO Technic Lamborghini");
INSERT INTO Gift VALUES (203,63,"Barbie Estate Dolls House and 3 Dolls");
INSERT INTO Gift VALUES (204,108,"Beast Lab Core Line Shark Playset");
INSERT INTO Gift VALUES (205,141,"LEGO Harry Potter Dobby the House-Elf Figure");
INSERT INTO Gift VALUES (206,196,"DesignaFriend Connie Fashion Designer Doll");
INSERT INTO Gift VALUES (207,1,"Nerf Elite 2.0 Double Punch Blaster");
INSERT INTO Gift VALUES (208,101,"Beast Lab Core Line Shark Playset");
INSERT INTO Gift VALUES (209,2,"Chad Valley Wooden Pizza");
INSERT INTO Gift VALUES (210,127,"DesignaFriend Connie Fashion Designer Doll");
INSERT INTO Gift VALUES (211,131,"LEGO Star WarsAhsoka Clone Trooper");
INSERT INTO Gift VALUES (212,89,"Barbie Estate Dolls House and 3 Dolls");
INSERT INTO Gift VALUES (213,115,"Chad Valley Trevor Talk Back Dino");
INSERT INTO Gift VALUES (214,28,"Chad Valley Trevor Talk Back Dino");
INSERT INTO Gift VALUES (215,70,"Little Live Pets – My Puppy’s Home Dalmatian Edition");
INSERT INTO Gift VALUES (216,73,"Little Live Pets – My Puppy’s Home Dalmatian Edition");
INSERT INTO Gift VALUES (217,156,"Squishmallows Drew the Mint Dragon");
INSERT INTO Gift VALUES (218,93,"Gabby's Dollhouse Cat Friendship Cruise Ship Playset");
INSERT INTO Gift VALUES (219,148,"Chad Valley Wooden Pizza");
INSERT INTO Gift VALUES (220,156,"LEGO Star WarsAhsoka Clone Trooper");
INSERT INTO Gift VALUES (221,41,"Squishmallows Drew the Mint Dragon");
INSERT INTO Gift VALUES (222,89,"Chad Valley Wooden Pizza");
INSERT INTO Gift VALUES (223,98,"DesignaFriend Connie Fashion Designer Doll");
INSERT INTO Gift VALUES (224,31,"Chad Valley Wooden 2 in 1 Café");
INSERT INTO Gift VALUES (225,38,"Barbie Estate Dolls House and 3 Dolls");
INSERT INTO Gift VALUES (226,80,"LEGO Harry Potter Dobby the House-Elf Figure");
INSERT INTO Gift VALUES (227,179,"Squishmallows Drew the Mint Dragon");
INSERT INTO Gift VALUES (228,187,"LEGO Technic Lamborghini");
INSERT INTO Gift VALUES (229,54,"Beast Lab Core Line Shark Playset");
INSERT INTO Gift VALUES (230,150,"Nerf Elite 2.0 Double Punch Blaster");
INSERT INTO Gift VALUES (231,160,"Hot Wheels Monster Trucks Ultimate Crush Yard Playset");
INSERT INTO Gift VALUES (232,5,"Fingerlings Monkey Pink - Harmony");
INSERT INTO Gift VALUES (233,183,"Bitzee Interactive Digital Pet");
INSERT INTO Gift VALUES (234,114,"Bitzee Interactive Digital Pet");
INSERT INTO Gift VALUES (235,100,"Squishmallows Drew the Mint Dragon");
INSERT INTO Gift VALUES (236,142,"Chad Valley Wooden Pizza");
INSERT INTO Gift VALUES (237,111,"Gabby's Dollhouse Cat Friendship Cruise Ship Playset");
INSERT INTO Gift VALUES (238,165,"DesignaFriend Connie Fashion Designer Doll");
INSERT INTO Gift VALUES (239,186,"Chad Valley Wooden Pizza");
INSERT INTO Gift VALUES (240,47,"Chad Valley Wooden 2 in 1 Café");
INSERT INTO Gift VALUES (241,77,"LEGO Star WarsAhsoka Clone Trooper");
INSERT INTO Gift VALUES (242,176,"Furby Purple Interactive Toy Plush");
INSERT INTO Gift VALUES (243,164,"Fingerlings Monkey Pink - Harmony");
INSERT INTO Gift VALUES (244,170,"LEGO Technic Lamborghini");
INSERT INTO Gift VALUES (245,7,"Squishmallows Drew the Mint Dragon");
INSERT INTO Gift VALUES (246,138,"Chad Valley Wooden 2 in 1 Café");
INSERT INTO Gift VALUES (247,181,"Chad Valley Wooden Pizza");
INSERT INTO Gift VALUES (248,54,"Bitzee Interactive Digital Pet");
INSERT INTO Gift VALUES (249,117,"Furby Purple Interactive Toy Plush");
INSERT INTO Gift VALUES (250,191,"Fingerlings Monkey Pink - Harmony");
INSERT INTO Gift VALUES (251,68,"LEGO Harry Potter Dobby the House-Elf Figure");
INSERT INTO Gift VALUES (252,147,"Furby Purple Interactive Toy Plush");
INSERT INTO Gift VALUES (253,175,"MGA's Miniverse – Make it Mini Food: Dine");
INSERT INTO Gift VALUES (254,75,"Teenage Mutant Ninja Turtles Pizza Delivery Van");
INSERT INTO Gift VALUES (255,12,"LEGO Star WarsAhsoka Clone Trooper");
INSERT INTO Gift VALUES (256,29,"Hot Wheels Monster Trucks Ultimate Crush Yard Playset");
INSERT INTO Gift VALUES (257,18,"Furby Purple Interactive Toy Plush");
INSERT INTO Gift VALUES (258,64,"MGA's Miniverse – Make it Mini Food: Dine");
INSERT INTO Gift VALUES (259,40,"Barbie Estate Dolls House and 3 Dolls");
INSERT INTO Gift VALUES (260,163,"Furby Purple Interactive Toy Plush");
INSERT INTO Gift VALUES (261,138,"LEGO Harry Potter Dobby the House-Elf Figure");
INSERT INTO Gift VALUES (262,101,"Bitzee Interactive Digital Pet");
INSERT INTO Gift VALUES (263,142,"Hot Wheels Monster Trucks Ultimate Crush Yard Playset");
INSERT INTO Gift VALUES (264,76,"LEGO Technic Lamborghini");
INSERT INTO Gift VALUES (265,193,"Gabby's Dollhouse Cat Friendship Cruise Ship Playset");
INSERT INTO Gift VALUES (266,92,"Barbie Estate Dolls House and 3 Dolls");
INSERT INTO Gift VALUES (267,85,"DesignaFriend Connie Fashion Designer Doll");
INSERT INTO Gift VALUES (268,30,"Squishmallows Drew the Mint Dragon");
INSERT INTO Gift VALUES (269,180,"LEGO Harry Potter Dobby the House-Elf Figure");
INSERT INTO Gift VALUES (270,107,"Fingerlings Monkey Pink - Harmony");
INSERT INTO Gift VALUES (271,198,"Hot Wheels Monster Trucks Ultimate Crush Yard Playset");
INSERT INTO Gift VALUES (272,72,"Nerf Elite 2.0 Double Punch Blaster");
INSERT INTO Gift VALUES (273,52,"Gabby's Dollhouse Cat Friendship Cruise Ship Playset");
INSERT INTO Gift VALUES (274,15,"Hot Wheels Monster Trucks Ultimate Crush Yard Playset");
INSERT INTO Gift VALUES (275,105,"Furby Purple Interactive Toy Plush");
INSERT INTO Gift VALUES (276,62,"Furby Purple Interactive Toy Plush");
INSERT INTO Gift VALUES (277,106,"MGA's Miniverse – Make it Mini Food: Dine");
INSERT INTO Gift VALUES (278,68,"Chad Valley Wooden Pizza");
INSERT INTO Gift VALUES (279,56,"Teenage Mutant Ninja Turtles Pizza Delivery Van");
INSERT INTO Gift VALUES (280,22,"LEGO Star WarsAhsoka Clone Trooper");
INSERT INTO Gift VALUES (281,199,"Fingerlings Monkey Pink - Harmony");
INSERT INTO Gift VALUES (282,152,"Hot Wheels Monster Trucks Ultimate Crush Yard Playset");
INSERT INTO Gift VALUES (283,37,"Chad Valley Wooden Pizza");
INSERT INTO Gift VALUES (284,195,"Fingerlings Monkey Pink - Harmony");
INSERT INTO Gift VALUES (285,138,"Chad Valley Wooden 2 in 1 Café");
INSERT INTO Gift VALUES (286,170,"Beast Lab Core Line Shark Playset");
INSERT INTO Gift VALUES (287,139,"DesignaFriend Connie Fashion Designer Doll");
INSERT INTO Gift VALUES (288,33,"MGA's Miniverse – Make it Mini Food: Dine");
INSERT INTO Gift VALUES (289,60,"LEGO Technic Lamborghini");
INSERT INTO Gift VALUES (290,30,"Gabby's Dollhouse Cat Friendship Cruise Ship Playset");
INSERT INTO Gift VALUES (291,199,"LEGO Harry Potter Dobby the House-Elf Figure");
INSERT INTO Gift VALUES (292,36,"LEGO Harry Potter Dobby the House-Elf Figure");
INSERT INTO Gift VALUES (293,198,"LEGO Harry Potter Dobby the House-Elf Figure");
INSERT INTO Gift VALUES (294,42,"Chad Valley Wooden 2 in 1 Café");
INSERT INTO Gift VALUES (295,56,"Gabby's Dollhouse Cat Friendship Cruise Ship Playset");
INSERT INTO Gift VALUES (296,152,"Fingerlings Monkey Pink - Harmony");
INSERT INTO Gift VALUES (297,65,"Squishmallows Drew the Mint Dragon");
INSERT INTO Gift VALUES (298,66,"Beast Lab Core Line Shark Playset");
INSERT INTO Gift VALUES (299,196,"Chad Valley Wooden 2 in 1 Café");
INSERT INTO Gift VALUES (300,12,"Gabby's Dollhouse Cat Friendship Cruise Ship Playset");
INSERT INTO Gift VALUES (301,18,"Fingerlings Monkey Pink - Harmony");
INSERT INTO Gift VALUES (302,58,"MGA's Miniverse – Make it Mini Food: Dine");
INSERT INTO Gift VALUES (303,109,"MGA's Miniverse – Make it Mini Food: Dine");
INSERT INTO Gift VALUES (304,171,"Teenage Mutant Ninja Turtles Pizza Delivery Van");
INSERT INTO Gift VALUES (305,45,"DesignaFriend Connie Fashion Designer Doll");
INSERT INTO Gift VALUES (306,178,"Chad Valley Wooden 2 in 1 Café");
INSERT INTO Gift VALUES (307,102,"LEGO Star WarsAhsoka Clone Trooper");
INSERT INTO Gift VALUES (308,79,"Teenage Mutant Ninja Turtles Pizza Delivery Van");
INSERT INTO Gift VALUES (309,164,"MGA's Miniverse – Make it Mini Food: Dine");
INSERT INTO Gift VALUES (310,51,"Furby Purple Interactive Toy Plush");
INSERT INTO Gift VALUES (311,163,"Nerf Elite 2.0 Double Punch Blaster");
INSERT INTO Gift VALUES (312,64,"Beast Lab Core Line Shark Playset");
INSERT INTO Gift VALUES (313,39,"Nerf Elite 2.0 Double Punch Blaster");
INSERT INTO Gift VALUES (314,47,"Little Live Pets – My Puppy’s Home Dalmatian Edition");
INSERT INTO Gift VALUES (315,96,"LEGO Star WarsAhsoka Clone Trooper");
INSERT INTO Gift VALUES (316,45,"Beast Lab Core Line Shark Playset");
INSERT INTO Gift VALUES (317,180,"Nerf Elite 2.0 Double Punch Blaster");
INSERT INTO Gift VALUES (318,108,"Hot Wheels Monster Trucks Ultimate Crush Yard Playset");
INSERT INTO Gift VALUES (319,105,"Hot Wheels Monster Trucks Ultimate Crush Yard Playset");
INSERT INTO Gift VALUES (320,146,"Fingerlings Monkey Pink - Harmony");
INSERT INTO Gift VALUES (321,129,"MGA's Miniverse – Make it Mini Food: Dine");
INSERT INTO Gift VALUES (322,98,"Hot Wheels Monster Trucks Ultimate Crush Yard Playset");
INSERT INTO Gift VALUES (323,57,"LEGO Star WarsAhsoka Clone Trooper");
INSERT INTO Gift VALUES (324,109,"LEGO Technic Lamborghini");
INSERT INTO Gift VALUES (325,76,"Gabby's Dollhouse Cat Friendship Cruise Ship Playset");
INSERT INTO Gift VALUES (326,127,"Hot Wheels Monster Trucks Ultimate Crush Yard Playset");
INSERT INTO Gift VALUES (327,147,"LEGO Technic Lamborghini");
INSERT INTO Gift VALUES (328,54,"Fingerlings Monkey Pink - Harmony");
INSERT INTO Gift VALUES (329,72,"Fingerlings Monkey Pink - Harmony");
INSERT INTO Gift VALUES (330,77,"Squishmallows Drew the Mint Dragon");
INSERT INTO Gift VALUES (331,22,"Beast Lab Core Line Shark Playset");
INSERT INTO Gift VALUES (332,99,"Gabby's Dollhouse Cat Friendship Cruise Ship Playset");
INSERT INTO Gift VALUES (333,83,"LEGO Harry Potter Dobby the House-Elf Figure");
INSERT INTO Gift VALUES (334,87,"Fingerlings Monkey Pink - Harmony");
INSERT INTO Gift VALUES (335,196,"Teenage Mutant Ninja Turtles Pizza Delivery Van");
INSERT INTO Gift VALUES (336,156,"Bitzee Interactive Digital Pet");
INSERT INTO Gift VALUES (337,20,"Bitzee Interactive Digital Pet");
INSERT INTO Gift VALUES (338,48,"Hot Wheels Monster Trucks Ultimate Crush Yard Playset");
INSERT INTO Gift VALUES (339,6,"LEGO Technic Lamborghini");
INSERT INTO Gift VALUES (340,73,"Furby Purple Interactive Toy Plush");
INSERT INTO Gift VALUES (341,47,"Chad Valley Wooden Pizza");
INSERT INTO Gift VALUES (342,146,"DesignaFriend Connie Fashion Designer Doll");
INSERT INTO Gift VALUES (343,193,"Hot Wheels Monster Trucks Ultimate Crush Yard Playset");
INSERT INTO Gift VALUES (344,200,"Beast Lab Core Line Shark Playset");
INSERT INTO Gift VALUES (345,131,"Little Live Pets – My Puppy’s Home Dalmatian Edition");
INSERT INTO Gift VALUES (346,198,"Fingerlings Monkey Pink - Harmony");
INSERT INTO Gift VALUES (347,81,"LEGO Star WarsAhsoka Clone Trooper");
INSERT INTO Gift VALUES (348,6,"Chad Valley Trevor Talk Back Dino");
INSERT INTO Gift VALUES (349,22,"LEGO Technic Lamborghini");
INSERT INTO Gift VALUES (350,162,"Gabby's Dollhouse Cat Friendship Cruise Ship Playset");
INSERT INTO Gift VALUES (351,41,"LEGO Star WarsAhsoka Clone Trooper");
INSERT INTO Gift VALUES (352,20,"Chad Valley Wooden 2 in 1 Café");
INSERT INTO Gift VALUES (353,177,"LEGO Technic Lamborghini");
INSERT INTO Gift VALUES (354,31,"Furby Purple Interactive Toy Plush");
INSERT INTO Gift VALUES (355,99,"LEGO Star WarsAhsoka Clone Trooper");
INSERT INTO Gift VALUES (356,52,"DesignaFriend Connie Fashion Designer Doll");
INSERT INTO Gift VALUES (357,128,"LEGO Technic Lamborghini");
INSERT INTO Gift VALUES (358,169,"Little Live Pets – My Puppy’s Home Dalmatian Edition");
INSERT INTO Gift VALUES (359,182,"LEGO Technic Lamborghini");
INSERT INTO Gift VALUES (360,81,"Gabby's Dollhouse Cat Friendship Cruise Ship Playset");
INSERT INTO Gift VALUES (361,53,"Gabby's Dollhouse Cat Friendship Cruise Ship Playset");
INSERT INTO Gift VALUES (362,94,"Furby Purple Interactive Toy Plush");
INSERT INTO Gift VALUES (363,66,"Hot Wheels Monster Trucks Ultimate Crush Yard Playset");
INSERT INTO Gift VALUES (364,77,"Beast Lab Core Line Shark Playset");
INSERT INTO Gift VALUES (365,151,"LEGO Technic Lamborghini");
INSERT INTO Gift VALUES (366,153,"Beast Lab Core Line Shark Playset");
INSERT INTO Gift VALUES (367,172,"Furby Purple Interactive Toy Plush");
INSERT INTO Gift VALUES (368,39,"Chad Valley Wooden 2 in 1 Café");
INSERT INTO Gift VALUES (369,157,"Chad Valley Wooden 2 in 1 Café");
INSERT INTO Gift VALUES (370,139,"Barbie Estate Dolls House and 3 Dolls");
INSERT INTO Gift VALUES (371,169,"Barbie Estate Dolls House and 3 Dolls");
INSERT INTO Gift VALUES (372,15,"Little Live Pets – My Puppy’s Home Dalmatian Edition");
INSERT INTO Gift VALUES (373,137,"Chad Valley Wooden 2 in 1 Café");
INSERT INTO Gift VALUES (374,47,"Beast Lab Core Line Shark Playset");
INSERT INTO Gift VALUES (375,22,"Furby Purple Interactive Toy Plush");
INSERT INTO Gift VALUES (376,183,"LEGO Harry Potter Dobby the House-Elf Figure");
INSERT INTO Gift VALUES (377,166,"MGA's Miniverse – Make it Mini Food: Dine");
INSERT INTO Gift VALUES (378,144,"Beast Lab Core Line Shark Playset");
INSERT INTO Gift VALUES (379,167,"Fingerlings Monkey Pink - Harmony");
INSERT INTO Gift VALUES (380,33,"LEGO Technic Lamborghini");
INSERT INTO Gift VALUES (381,62,"Beast Lab Core Line Shark Playset");
INSERT INTO Gift VALUES (382,9,"Beast Lab Core Line Shark Playset");
INSERT INTO Gift VALUES (383,149,"Furby Purple Interactive Toy Plush");
INSERT INTO Gift VALUES (384,97,"Chad Valley Trevor Talk Back Dino");
INSERT INTO Gift VALUES (385,115,"Fingerlings Monkey Pink - Harmony");
INSERT INTO Gift VALUES (386,120,"LEGO Harry Potter Dobby the House-Elf Figure");
INSERT INTO Gift VALUES (387,54,"Chad Valley Trevor Talk Back Dino");
INSERT INTO Gift VALUES (388,143,"Gabby's Dollhouse Cat Friendship Cruise Ship Playset");
INSERT INTO Gift VALUES (389,117,"Fingerlings Monkey Pink - Harmony");
INSERT INTO Gift VALUES (390,77,"Furby Purple Interactive Toy Plush");
INSERT INTO Gift VALUES (391,163,"Teenage Mutant Ninja Turtles Pizza Delivery Van");
INSERT INTO Gift VALUES (392,160,"LEGO Star WarsAhsoka Clone Trooper");
INSERT INTO Gift VALUES (393,170,"Gabby's Dollhouse Cat Friendship Cruise Ship Playset");
INSERT INTO Gift VALUES (394,111,"LEGO Star WarsAhsoka Clone Trooper");
INSERT INTO Gift VALUES (395,175,"Bitzee Interactive Digital Pet");
INSERT INTO Gift VALUES (396,173,"Chad Valley Wooden 2 in 1 Café");
INSERT INTO Gift VALUES (397,10,"DesignaFriend Connie Fashion Designer Doll");
INSERT INTO Gift VALUES (398,192,"Fingerlings Monkey Pink - Harmony");
INSERT INTO Gift VALUES (399,104,"Squishmallows Drew the Mint Dragon");
INSERT INTO Gift VALUES (400,100,"LEGO Harry Potter Dobby the House-Elf Figure");
