CREATE TABLE Route (
    routeID INT NOT NULL,
    depCode VARCHAR(3) NOT NULL,
    arrCode VARCHAR(3) NOT NULL,
    stop1code VARCHAR(3),
    stop2code VARCHAR(3),
    FOREIGN KEY (depCode)
        REFERENCES Airport (code),
    FOREIGN KEY (arrCode)
        REFERENCES Airport (code),
    FOREIGN KEY (stop1code)
        REFERENCES Airport (code),
    FOREIGN KEY (stop2code)
        REFERENCES Airport (code),
    PRIMARY KEY (routeID)
);

INSERT INTO Route VALUES (1279,"GLA","IBZ","BRU",NULL);
INSERT INTO Route VALUES (1329,"MMX","LHR",NULL,NULL);
INSERT INTO Route VALUES (1902,"VNO","EDI","BER","LHR");
INSERT INTO Route VALUES (1924,"SAW","LHR",NULL,NULL);
INSERT INTO Route VALUES (2716,"NAP","MAN",NULL,NULL);
INSERT INTO Route VALUES (2847,"LPL","ARN","AMS",NULL);
INSERT INTO Route VALUES (3187,"ATH","EDI",NULL,NULL);
INSERT INTO Route VALUES (3651,"MAN","FRA",NULL,NULL);
INSERT INTO Route VALUES (3976,"STN","CHQ","VIE",NULL);
INSERT INTO Route VALUES (4153,"BFS","BCN",NULL,NULL);
INSERT INTO Route VALUES (4551,"LGW","LAX","JFK","DEN");
INSERT INTO Route VALUES (4871,"STN","MUC",NULL,NULL);
INSERT INTO Route VALUES (5172,"BHX","FCO",NULL,NULL);
INSERT INTO Route VALUES (5281,"HEL","LPL","AMS",NULL);
INSERT INTO Route VALUES (5765,"BHX","BUD",NULL,NULL);
INSERT INTO Route VALUES (6232,"ABZ","LSI",NULL,NULL);
INSERT INTO Route VALUES (6982,"SVQ","GLA","MAD",NULL);
INSERT INTO Route VALUES (7120,"EDI","SVQ",NULL,NULL);
INSERT INTO Route VALUES (7625,"BRS","LIS",NULL,NULL);
INSERT INTO Route VALUES (9214,"EDI","DUB",NULL,NULL);
