CREATE TABLE Staff (
    staffID INT NOT NULL,
    title VARCHAR(6) NOT NULL,
    lastName VARCHAR(30),
    role VARCHAR(15) NOT NULL,
    PRIMARY KEY (staffID)
);

INSERT INTO Staff VALUES 1,"Miss","Adams","Teacher");
INSERT INTO Staff VALUES 2,"Mr","Barton","Teacher");
INSERT INTO Staff VALUES 3,"Mrs","Bassinger","Teacher");
INSERT INTO Staff VALUES 4,"Mr","Baxter","Teacher");
INSERT INTO Staff VALUES 5,"Miss","Bettany","SfLA");
INSERT INTO Staff VALUES 6,"Miss","Betterton","Secretary");
INSERT INTO Staff VALUES 7,"Mrs","Booth","Teacher");
INSERT INTO Staff VALUES 8,"Mrs","Briscoe","Teacher");
INSERT INTO Staff VALUES 9,"Mr","Brisley","Teacher");
INSERT INTO Staff VALUES 10,"Mr","Bronson","Teacher");
INSERT INTO Staff VALUES 11,"Miss","Brooks","Teacher");
INSERT INTO Staff VALUES 12,"Mr","Butterworth","Teacher");
INSERT INTO Staff VALUES 13,"Miss","Carver","Teacher");
INSERT INTO Staff VALUES 14,"Miss","Clarke","Teacher");
INSERT INTO Staff VALUES 15,"Mrs","Cooney","Cleaner");
INSERT INTO Staff VALUES 16,"Mr","Curtis","Head of Year");
INSERT INTO Staff VALUES 17,"Mr","Dean","Teacher");
INSERT INTO Staff VALUES 18,"Mr","Devereaux","Teacher");
INSERT INTO Staff VALUES 19,"Mrs","Dunlop","Teacher");
INSERT INTO Staff VALUES 20,"Mrs","Dunne","Teacher");
INSERT INTO Staff VALUES 21,"Miss","Dyson","Teacher");
INSERT INTO Staff VALUES 22,"Mrs","Evans","Teacher");
INSERT INTO Staff VALUES 23,"Mr","Foster","Teacher");
INSERT INTO Staff VALUES 24,"Miss","Fraser","Teacher");
INSERT INTO Staff VALUES 25,"Mr","Garfield","Janitor");
INSERT INTO Staff VALUES 26,"Miss","Gayle","Deputy Head Teacher");
INSERT INTO Staff VALUES 27,"Mrs","Girling","Teacher");
INSERT INTO Staff VALUES 28,"Miss","Gordon","Teacher");
INSERT INTO Staff VALUES 29,"Mrs","Gossage","Secretary");
INSERT INTO Staff VALUES 30,"Mr","Greenman","Janitor");
INSERT INTO Staff VALUES 31,"Miss","Griffiths","Teacher");
INSERT INTO Staff VALUES 32,"Mr","Griffiths","Janitor");
INSERT INTO Staff VALUES 33,"Mr","Hankin","Teacher");
INSERT INTO Staff VALUES 34,"Mr","Hargreaves","Teacher");
INSERT INTO Staff VALUES 35,"Mrs","Harris","Cleaner");
INSERT INTO Staff VALUES 36,"Miss","Hartley","Teacher");
INSERT INTO Staff VALUES 37,"Mrs","Harvey","Teacher");
INSERT INTO Staff VALUES 38,"Mr","Hicks","Teacher");
INSERT INTO Staff VALUES 39,"Mrs","Holmes","Teacher");
INSERT INTO Staff VALUES 40,"Mr","Hopwood","Teacher");
INSERT INTO Staff VALUES 41,"Mr","Howard","Head of Year");
INSERT INTO Staff VALUES 42,"Miss","Janet","Secretary");
INSERT INTO Staff VALUES 43,"Miss","Janowitz","Teacher");
INSERT INTO Staff VALUES 44,"Mr","Jones","Teacher");
INSERT INTO Staff VALUES 45,"Mrs","Jones","Teacher");
INSERT INTO Staff VALUES 46,"Miss","Jordan","Teacher");
INSERT INTO Staff VALUES 47,"Mrs","Joseph","Business Manager");
INSERT INTO Staff VALUES 48,"Mr","Keating","Teacher");
INSERT INTO Staff VALUES 49,"Mrs","Keele","Head Teacher");
INSERT INTO Staff VALUES 50,"Mrs","Kennedy","Teacher");
INSERT INTO Staff VALUES 51,"Mr","King","Teacher");
INSERT INTO Staff VALUES 52,"Mr","Knowles","Teacher");
INSERT INTO Staff VALUES 53,"Madame","Lefevre","Teacher");
INSERT INTO Staff VALUES 54,"Mr","Legge","Teacher");
INSERT INTO Staff VALUES 55,"Miss","Lexington","Teacher");
INSERT INTO Staff VALUES 56,"Mrs","Maguire","Secretary");
INSERT INTO Staff VALUES 57,"Mr","Malachy","Teacher");
INSERT INTO Staff VALUES 58,"Mr","Malcolm","Teacher");
INSERT INTO Staff VALUES 59,"Mr","Manyeke","Teacher");
INSERT INTO Staff VALUES 60,"Miss","Mather","Teacher");
INSERT INTO Staff VALUES 61,"Mr","McCartney","Teacher");
INSERT INTO Staff VALUES 62,"Miss","McCluskey","Deputy Head Teacher");
INSERT INTO Staff VALUES 63,"Mr","McDonnell","Teacher");
INSERT INTO Staff VALUES 64,"Mr","McGuffey","Teacher");
INSERT INTO Staff VALUES 65,"Miss","McIlroy","Office Manager");
INSERT INTO Staff VALUES 66,"Mr","McKenzie","Teacher");
INSERT INTO Staff VALUES 67,"Miss","Miles","Teacher");
INSERT INTO Staff VALUES 68,"Mr","Mitchell","Janitor");
INSERT INTO Staff VALUES 69,"Mr","Mitchell","Teacher");
INSERT INTO Staff VALUES 70,"Mrs","Monroe","Teacher");
INSERT INTO Staff VALUES 71,"Miss","Mooney","Teacher");
INSERT INTO Staff VALUES 72,"Mrs","Moorcroft","Teacher");
INSERT INTO Staff VALUES 73,"Miss","O'Keefe","Nurse");
INSERT INTO Staff VALUES 74,"Mr","Parkes","Teacher");
INSERT INTO Staff VALUES 75,"Mr","Parrott","Teacher");
INSERT INTO Staff VALUES 76,"Miss","Parsons","Teacher");
INSERT INTO Staff VALUES 77,"Miss","Partridge","Teacher");
INSERT INTO Staff VALUES 78,"Miss","Peterson","Teacher");
INSERT INTO Staff VALUES 79,"Mr","Price","Teacher");
INSERT INTO Staff VALUES 80,"Mr","Rankin","Teacher");
INSERT INTO Staff VALUES 81,"Ms","Rawlinson","Teacher");
INSERT INTO Staff VALUES 82,"Mr","Raynesford","Teacher");
INSERT INTO Staff VALUES 83,"Mrs","Reagan","Teacher");
INSERT INTO Staff VALUES 84,"Mr","Robson","Teacher");
INSERT INTO Staff VALUES 85,"Miss","Saunders","Teacher");
INSERT INTO Staff VALUES 86,"Mrs","Schubert","Teacher");
INSERT INTO Staff VALUES 87,"Mr","Scott","Teacher");
INSERT INTO Staff VALUES 88,"Mr","Scott","Janitor");
INSERT INTO Staff VALUES 89,"Mr","Smart","Teacher");
INSERT INTO Staff VALUES 90,"Mrs","Stone","Teacher");
INSERT INTO Staff VALUES 91,"Miss","Summers","Teacher");
INSERT INTO Staff VALUES 92,"Mr","Sutcliffe","Teacher");
INSERT INTO Staff VALUES 93,"Mr","Swindells","Teacher");
INSERT INTO Staff VALUES 94,"Mrs","Thomas","Teacher");
INSERT INTO Staff VALUES 95,"Mr","Thompson","Janitor");
INSERT INTO Staff VALUES 96,"Mr","Urdy","Teacher");
INSERT INTO Staff VALUES 97,"Mr","van der Groot","Teacher");
INSERT INTO Staff VALUES 98,"Miss","Washington","Teacher");
