INSERT INTO taxi VALUES (1,"AZ68 KOS","Mercury","Grand Marquis","Goldenrod");
INSERT INTO taxi VALUES (2,"PX02 UGR","Mitsubishi","Pajero","Puce");
INSERT INTO taxi VALUES (3,"ZI62 IWM","Nissan","Titan","Crimson");
INSERT INTO taxi VALUES (4,"UF07 KFM","Volvo","V70","Mauv");
INSERT INTO taxi VALUES (5,"HD58 OZI","Ford","Crown Victoria","Teal");
INSERT INTO taxi VALUES (6,"RV16 VNO","Isuzu","Rodeo","Green");
INSERT INTO taxi VALUES (7,"XO57 RUD","Toyota","Corolla","Blue");
INSERT INTO taxi VALUES (8,"VQ52 BWX","Mazda","MX-6","Khaki");
INSERT INTO taxi VALUES (9,"PL53 TXF","Plymouth","Grand Voyager","Aquamarine");
INSERT INTO taxi VALUES (10,"FA66 XBX","Dodge","Caliber","Khaki");
INSERT INTO taxi VALUES (11,"TM11 UZS","Chevrolet","Colorado","Puce");
INSERT INTO taxi VALUES (12,"FL06 TIB","Buick","LeSabre","Crimson");
INSERT INTO taxi VALUES (13,"CJ57 ZZL","Buick","LaCrosse","Teal");
INSERT INTO taxi VALUES (14,"WC62 PLB","Mercury","Sable","Orange");
INSERT INTO taxi VALUES (15,"YU69 RQF","Infiniti","J","Blue");
INSERT INTO taxi VALUES (16,"FN69 HHG","Land Rover","LR2","Fuscia");
INSERT INTO taxi VALUES (17,"WS03 WEC","Ford","Explorer","Mauv");
INSERT INTO taxi VALUES (18,"ID50 QED","Hyundai","Santa Fe","Purple");
INSERT INTO taxi VALUES (19,"FK06 SLO","Suzuki","SJ 410","Teal");
INSERT INTO taxi VALUES (20,"PW01 VUL","Audi","4000s","Turquoise");
